### ISSUE TITLE
Were MFAAS dependencies moved to https://zowe.jfrog.io/?

### ISSUE THREAD

**Issue by matthewgrider** [zowe/sample-spring-boot-api-service#122]
Having issue with fresh build on a new machine (cannot grab MFAAS dependencies). Looks like  https://gizaartifactory.jfrog.io/ is no more? If that is the case it might be good to update some of the [gradle.properties](https://github.com/zowe/sample-spring-boot-api-service/blob/master/zowe-rest-api-sample-spring/gradle.properties) to clarify the change to https://zowe.jfrog.io/ mentioned [here](https://github.com/zowe/docs-site/issues/853). Also is there now a new user and password for that repo?

**Comment by balhar-jakub** [comment]
As the API Mediation Layer became more tightly integrated into the Zowe the artifacts and their locations chaged. 

The locations and artifacts are outlined here: https://docs.zowe.org/stable/extend/extend-apiml/onboard-plain-java-enabler.html#gradle-build-automation-system

The new repo is public and there are no credentials needed anymore.

**Comment by plavjanik** [comment]
This repository has been updated to use the working artifact repositories.
