### ISSUE TITLE
Figure out how to let other users know that this repo has changed so they should upgrade

### ISSUE THREAD

**Issue by vvvlc** [zowe/sample-spring-boot-api-service#13]
We need a way how to let other teams (REST API Sample users) know that this repo has changed (eg vulnerability fix) so they update they code accordingly.

This is an outcome of architecture discussion on 6/24/2019

**Comment by dkelosky** [comment]
I'm thinking that we can close this issue based on current plans for creating a sample versus an "SDK".  We can open a future issue if people have specific problems to address.  @vvvlc,  do you agree?

**Comment by vvvlc** [comment]
yes
