### ISSUE TITLE
Setting messageReason and messageAction

### ISSUE THREAD

**Issue by dkelosky** [zowe/sample-spring-boot-api-service#53]
Because I could not find a way to supply optional properties like messageReason and messageAction to the error-handling capabilities supplied by the commons package, I simply have not used them.

Can you confirm if this is true?

Reported by @gejohnston

**Comment by dkelosky** [comment]
@plavjanik the `optional` message info [here](https://github.com/zowe/sample-spring-boot-api-service/blob/master/zowe-rest-api-sample-spring/docs/error-handling.md#rules-for-messages) - how are things like `messageReason` set?

**Comment by plavjanik** [comment]
Hello Gene and Dan,

the current implementation (migrated from the original SDK) does not read the `messageReason` and `messageAction` properties from the YAML files and there is no way how to add them to the message programmatically later. 

I think that it makes sense to make it possible in the future. I mean both defining it in the YAML and updating programmatically.

I am starting to work on i18n and one part of it is to make possible to define these messages in other languages so I will start with adding these optional fields.

Best regards,
Petr

**Comment by plavjanik** [comment]
#63 adds support for these fields
