### ISSUE TITLE
URI Pattern Inside and Outside of API ML

### ISSUE THREAD

**Issue by dkelosky** [zowe/sample-spring-boot-api-service#66]
If we follow [this](https://github.com/zowe/sample-spring-boot-api-service/blob/master/zowe-rest-api-sample-spring/docs/zowe-integrate-with-apiml.md#setting-api-service-metadata): 

```
   routes:
        - gatewayUrl: api/v1
          serviceUrl: /api/v1
```

We may have an endpoint outside of the API ML that is: `/api/v1/status`.  

Then, through the API ML, we would then have `/api/v1/servicename/status`

A concern is that this might make it difficult to be a client for both cases.  Is that valid or is this normal in an API ML?

**Comment by plavjanik** [comment]
What would you suggest?

To have `/serviceid/api/v1/status` at the API Gateway?

That would make more sense to me now. If we want to change it, we have to discuss it with the API squad and do it before LTS.

**Comment by dkelosky** [comment]
It's a pretty disruptive change, but I think it would be less confusing to teams.  I can ask them to comment here, would that be helpful?

**Comment by plavjanik** [comment]
I think that the issue should be opened in zowe/api-layer. SDK just follows it and then we can ask teams what they think if API squad agrees that it makes sense.

**Comment by dkelosky** [comment]
Good point - I coped the issue there and will close this one.  Thanks
