### ISSUE TITLE
Request: make RegisterToApiLayer part of zowe commons

### ISSUE THREAD

**Issue by tucker01** [zowe/sample-spring-boot-api-service#69]
We have code in our service that registers to the API layer. We modeled it after the provided sample:

https://github.com/zowe/sample-spring-boot-api-service/blob/master/zowe-rest-api-sample-spring/src/main/java/org/zowe/sample/apiservice/zowe/RegisterToApiLayer.java

Would it be possible (or make sense) to include this with Zowe commons jar?

**Comment by plavjanik** [comment]
Yes, that makes sense. Thanks for noticing it.

**Comment by plavjanik** [comment]
This would be great to do before 1.0.0
