### ISSUE TITLE
Relicense Repository - EPL+Apache

### ISSUE THREAD

**Issue by MarkAckert** [zowe/sample-spring-boot-api-service#71]
As this repository contains sample source code intended to be downloaded and expanded upon, it would be better suited with an EPL+Apache 2.0 dual license.

The OMP Governing Board has approved EPL-2.0 license waivers for sample repositories in Zowe, replaced by the dual license.

To re-license this repository, all contributors should consent by responding to this issue in the affirmative.

**Comment by MarkAckert** [comment]
+1 to relicense

**Comment by dkelosky** [comment]
affirmative

**Comment by plavjanik** [comment]
+1 to relicense

**Comment by supmi01** [comment]
@plavjanik I am wondering. Does this repo point to all the integration enablers we have or just to "Plan Java" Enabler? My point is I think we need to make sure all int. enablers are considered to get relicensed.

**Comment by VitekVlcek-Broadcom** [comment]
+1 to relicense

**Comment by plavjanik** [comment]
Still valid
