### ISSUE TITLE
SafPlatformUser - Valid Username Blank Password

### ISSUE THREAD

**Issue by dkelosky** [zowe/sample-spring-boot-api-service#72]
Reporting for another team - SafPlatformUser() does not reject a valid user name with a blank password when called through the SDK basic auth code.  

I haven't had a chance to independently verify but capturing here until it is verified.

**Comment by dkelosky** [comment]
Update - appears to only occur on CA Top Secret systems

**Comment by plavjanik** [comment]
It happens on all systems when the user ID of the server has the authority to pass SURROGAT class checks. More details and fix is in #78

**Comment by plavjanik** [comment]
Fixed in [`v0.7.1`](https://github.com/zowe/sample-spring-boot-api-service/releases/tag/v0.7.1)
