### ISSUE TITLE
Security Documentation - Commands and Requirements Don't Match

### ISSUE THREAD

**Issue by awharn** [zowe/sample-spring-boot-api-service#89]
The commands provided and documented required permissions do not match:
https://github.com/zowe/sample-spring-boot-api-service/blob/master/zowe-rest-api-sample-spring/docs/zos-security.md

The `Required Security Access for Development` section states that access requirements need to be `BPX.DAEMON = READ` and `BPX.SERVER = READ`.

The commands listed have `BPX.DAEMON = UPDATE`.

**Comment by plavjanik** [comment]
The commands are correct. The required access level to BPX.DAEMON is UPDATE.

**Comment by plavjanik** [comment]
The documentation has been fixed.
